from pathlib import Path

import pandas as pd

from src.audit import log_event
from src.data import PROJECT_ROOT


PREDICTION_DIR = PROJECT_ROOT / "reports" / "predictions"
REPORT_DIR = PROJECT_ROOT / "reports" / "clinical_reports"

REPORT_DIR.mkdir(parents=True, exist_ok=True)


def generate_report(prediction_file: Path):

    prediction_data = pd.read_csv(prediction_file)

    row = prediction_data.iloc[0]

    case_id = row["Case_ID"]
    predicted_diagnosis = row["Predicted_Diagnosis"]
    malignant_probability = float(row["Malignant_Probability"])
    threshold = float(row["Threshold"])
    risk_level = row["Risk_Level"]

    report_content = f"""
============================================================
INTELLIGENT TUMOR DECISION SUPPORT SYSTEM
CLINICAL RISK ASSESSMENT REPORT
============================================================

Case ID
-------
{case_id}

Prediction Summary
------------------
Predicted Classification : {predicted_diagnosis}

Malignant Probability    : {malignant_probability:.2%}

Risk Level               : {risk_level}

Decision Threshold Used  : {threshold:.2f}


Clinical Interpretation
-----------------------

"""

    if risk_level == "High":

        report_content += """
The model indicates a high predicted probability of malignancy.

This case should be prioritised for further clinical evaluation and
review by qualified healthcare professionals.

"""

    elif risk_level == "Moderate":

        report_content += """
The model indicates an elevated predicted risk of malignancy.

Additional clinical investigation and professional review are
recommended before making any diagnostic decision.

"""

    else:

        report_content += """
The model indicates a relatively low predicted probability of
malignancy.

However, a low-risk prediction does not rule out disease and should
not replace appropriate clinical examination and diagnostic testing.

"""

    report_content += f"""
Model Decision Information
--------------------------

The classification threshold used by the system is {threshold:.2f}.

Cases with a malignant probability greater than or equal to this
threshold are classified as malignant-risk cases.

The threshold was selected during model evaluation to improve
malignant-case recall and reduce false-negative predictions.


Important Safety Notice
-----------------------

This report is generated by an academic clinical decision-support
prototype.

The system is not clinically validated and must not be used as a
standalone diagnostic tool.

All predictions must be reviewed together with appropriate clinical
history, examination, imaging, pathology, and professional medical
judgement.

============================================================
END OF REPORT
============================================================
"""

    output_path = REPORT_DIR / f"{case_id}_clinical_report.txt"

    with open(
        output_path,
        "w",
        encoding="utf-8",
    ) as file:

        file.write(report_content)

    # -------------------------------------------------------
    # Log report generation in audit trail
    # -------------------------------------------------------

    log_event(
        case_id,
        "REPORT_GENERATED",
        (
            f"Clinical report created; "
            f"Prediction={predicted_diagnosis}; "
            f"Risk={risk_level}"
        ),
    )

    return output_path


def main():

    print("=" * 70)
    print("CLINICAL REPORT GENERATOR")
    print("=" * 70)

    prediction_files = list(
        PREDICTION_DIR.glob(
            "*_prediction.csv"
        )
    )

    if not prediction_files:

        print(
            "\nNo prediction files found."
        )

        print(
            "Run python -m src.predict first."
        )

        return

    # Use latest prediction file
    latest_file = max(
        prediction_files,
        key=lambda path: path.stat().st_mtime,
    )

    print(
        f"\nUsing prediction file: "
        f"{latest_file.name}"
    )

    report_path = generate_report(
        latest_file
    )

    print(
        "\nClinical report generated successfully."
    )

    print(
        f"\nReport saved to: "
        f"{report_path}"
    )


if __name__ == "__main__":
    main()